services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=wine_quality
    volumes:
      - "./wine_quality:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - airflow_default
networks:
  airflow_default:
    name: airflow_default